# Generated by Django 5.1.4 on 2026-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
