import type {
  CalendarEvent,
  Client,
  Comment,
  Deliverable,
  Mission,
  Notification,
  Project,
  User,
} from "@/types";

/**
 * Jeu de données de démonstration.
 * À remplacer par les appels API Django (voir src/services).
 */

export const users: User[] = [
  {
    id: "u1",
    first_name: "Amine",
    last_name: "Bekkari",
    email: "admin@bebaempire.com",
    phone: "+212 6 61 20 30 40",
    role: "admin",
    job_title: "Directeur d'agence",
    workload: 62,
    is_active: true,
    created_at: "2024-01-12",
  },
  {
    id: "u2",
    first_name: "Sara",
    last_name: "Lahlou",
    email: "sara@bebaempire.com",
    phone: "+212 6 12 45 78 90",
    role: "chef_projet",
    job_title: "Chef de projet senior",
    workload: 84,
    is_active: true,
    created_at: "2024-02-03",
  },
  {
    id: "u3",
    first_name: "Yassine",
    last_name: "Rami",
    email: "yassine@bebaempire.com",
    phone: "+212 6 55 44 33 22",
    role: "collaborateur",
    job_title: "Directeur artistique",
    workload: 91,
    is_active: true,
    created_at: "2024-03-18",
  },
  {
    id: "u4",
    first_name: "Nadia",
    last_name: "Fassi",
    email: "nadia@bebaempire.com",
    phone: "+212 6 77 88 99 00",
    role: "collaborateur",
    job_title: "Community manager",
    workload: 47,
    is_active: true,
    created_at: "2024-04-02",
  },
  {
    id: "u5",
    first_name: "Omar",
    last_name: "Benjelloun",
    email: "omar@atlasretail.com",
    phone: "+212 5 22 11 00 99",
    role: "client",
    job_title: "Directeur marketing",
    is_active: true,
    created_at: "2024-05-21",
  },
];

export const clients: Client[] = [
  {
    id: "c1",
    name: "Atlas Retail",
    industry: "Grande distribution",
    email: "contact@atlasretail.com",
    phone: "+212 5 22 11 00 99",
    address: "Casablanca, Maroc",
    status: "actif",
    contacts: [
      { id: "ct1", name: "Omar Benjelloun", email: "omar@atlasretail.com", position: "DirMarketing" },
    ],
    created_at: "2024-05-21",
  },
  {
    id: "c2",
    name: "Nova Finance",
    industry: "Services financiers",
    email: "hello@novafinance.io",
    phone: "+212 5 37 88 12 45",
    address: "Rabat, Maroc",
    status: "actif",
    contacts: [{ id: "ct2", name: "Leila Cherkaoui", email: "leila@novafinance.io", position: "CMO" }],
    created_at: "2024-06-14",
  },
  {
    id: "c3",
    name: "Green Origin",
    industry: "Agroalimentaire",
    email: "info@greenorigin.ma",
    address: "Marrakech, Maroc",
    status: "prospect",
    contacts: [],
    created_at: "2025-01-09",
  },
  {
    id: "c4",
    name: "Vertex Immo",
    industry: "Immobilier",
    email: "contact@verteximmo.ma",
    address: "Tanger, Maroc",
    status: "inactif",
    contacts: [],
    created_at: "2024-09-30",
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Refonte identité de marque",
    client_id: "c1",
    description: "Nouvelle charte graphique, logo et déclinaisons print & digital.",
    start_date: "2026-06-01",
    end_date: "2026-09-15",
    status: "en_cours",
    progress: 64,
    owner_id: "u2",
    created_at: "2026-05-20",
  },
  {
    id: "p2",
    name: "Campagne acquisition Q3",
    client_id: "c2",
    description: "Stratégie paid media multi-canal et création des assets.",
    start_date: "2026-07-01",
    end_date: "2026-10-01",
    status: "en_preparation",
    progress: 22,
    owner_id: "u2",
    created_at: "2026-06-10",
  },
  {
    id: "p3",
    name: "Lancement gamme bio",
    client_id: "c3",
    description: "Plan de communication 360 pour le lancement produit.",
    start_date: "2026-08-01",
    end_date: "2026-12-20",
    status: "brouillon",
    progress: 5,
    owner_id: "u1",
    created_at: "2026-07-02",
  },
  {
    id: "p4",
    name: "Site vitrine + SEO",
    client_id: "c4",
    description: "Refonte du site vitrine et optimisation du référencement.",
    start_date: "2026-02-01",
    end_date: "2026-06-30",
    status: "termine",
    progress: 100,
    owner_id: "u2",
    created_at: "2026-01-15",
  },
];

export const missions: Mission[] = [
  {
    id: "m1",
    title: "Direction artistique du nouveau logo",
    description: "Exploration de 3 pistes créatives et présentation client.",
    objective: "Valider une piste graphique avec le client.",
    strategy: "Moodboards, benchmark concurrentiel, 3 propositions.",
    resources: "Illustrator, banque d'images, 12h DA",
    priority: "haute",
    assignee_id: "u3",
    project_id: "p1",
    client_id: "c1",
    deadline: "2026-08-01",
    status: "en_cours",
    created_at: "2026-06-05",
  },
  {
    id: "m2",
    title: "Plan éditorial réseaux sociaux",
    description: "Calendrier éditorial 3 mois avec formats et angles.",
    objective: "Augmenter l'engagement de 20%.",
    strategy: "Piliers de contenus, formats courts, UGC.",
    resources: "Notion, Canva, 8h CM",
    priority: "normale",
    assignee_id: "u4",
    project_id: "p1",
    client_id: "c1",
    deadline: "2026-08-02",
    status: "livrable_depose",
    created_at: "2026-06-12",
  },
  {
    id: "m3",
    title: "Setup campagnes Meta Ads",
    description: "Structure de compte, audiences et tracking.",
    objective: "CPA cible < 12 €",
    strategy: "Advantage+, retargeting, exclusion acheteurs.",
    resources: "Business Manager, budget test 3k€",
    priority: "urgente",
    assignee_id: "u4",
    project_id: "p2",
    client_id: "c2",
    deadline: "2026-07-25",
    status: "validation_interne",
    created_at: "2026-06-28",
  },
  {
    id: "m4",
    title: "Production vidéo teaser",
    description: "Teaser 30s pour le lancement de la gamme bio.",
    objective: "Créer de l'attente avant le lancement.",
    strategy: "Tournage 1 jour, montage dynamique, sous-titres.",
    resources: "Équipe vidéo, studio, 3 jours",
    priority: "critique",
    assignee_id: "u3",
    project_id: "p3",
    client_id: "c3",
    deadline: "2026-07-30",
    status: "a_faire",
    created_at: "2026-07-05",
  },
  {
    id: "m5",
    title: "Audit SEO technique",
    description: "Audit complet et plan d'action priorisé.",
    objective: "Corriger les erreurs bloquantes d'indexation.",
    strategy: "Crawl, Core Web Vitals, netlinking.",
    resources: "Screaming Frog, GSC",
    priority: "faible",
    assignee_id: "u3",
    project_id: "p4",
    client_id: "c4",
    deadline: "2026-06-20",
    status: "termine",
    created_at: "2026-05-02",
  },
  {
    id: "m6",
    title: "Déclinaisons print charte",
    description: "Cartes de visite, papeterie, signalétique.",
    objective: "Homogénéiser les supports print.",
    strategy: "Gabarits InDesign réutilisables.",
    resources: "InDesign, imprimeur partenaire",
    priority: "normale",
    assignee_id: "u3",
    project_id: "p1",
    client_id: "c1",
    deadline: "2026-08-20",
    status: "envoye_client",
    created_at: "2026-06-30",
  },
  {
    id: "m7",
    title: "Landing page campagne",
    description: "Page de conversion dédiée à la campagne Q3.",
    objective: "Taux de conversion > 4%.",
    strategy: "A/B test des accroches, preuve sociale.",
    resources: "Figma, dev front 5j",
    priority: "haute",
    assignee_id: "u4",
    project_id: "p2",
    client_id: "c2",
    deadline: "2026-07-28",
    status: "corrections",
    created_at: "2026-07-01",
  },
];

export const deliverables: Deliverable[] = [
  {
    id: "d1",
    mission_id: "m2",
    name: "Plan-editorial-Q3.pdf",
    type: "pdf",
    url: "#",
    version: 2,
    size_kb: 1840,
    uploaded_by: "u4",
    status: "en_attente",
    created_at: "2026-07-20",
  },
  {
    id: "d2",
    mission_id: "m1",
    name: "Pistes-logo-v1.zip",
    type: "zip",
    url: "#",
    version: 1,
    size_kb: 24500,
    uploaded_by: "u3",
    status: "corrections",
    created_at: "2026-07-18",
  },
  {
    id: "d3",
    mission_id: "m6",
    name: "Charte-print-preview.png",
    type: "image",
    url: "#",
    version: 3,
    size_kb: 980,
    uploaded_by: "u3",
    status: "valide",
    created_at: "2026-07-22",
  },
  {
    id: "d4",
    mission_id: "m3",
    name: "Dashboard Looker Studio",
    type: "lien",
    url: "#",
    version: 1,
    uploaded_by: "u4",
    status: "en_attente",
    created_at: "2026-07-24",
  },
];

export const comments: Comment[] = [
  {
    id: "cm1",
    mission_id: "m1",
    author_id: "u2",
    body: "La piste 2 est la plus alignée avec le positionnement. @Yassine peux-tu décliner en monochrome ?",
    mentions: ["u3"],
    created_at: "2026-07-19T09:24:00Z",
  },
  {
    id: "cm2",
    mission_id: "m1",
    author_id: "u3",
    body: "Reçu, je livre les déclinaisons demain matin.",
    parent_id: "cm1",
    mentions: [],
    created_at: "2026-07-19T10:02:00Z",
  },
  {
    id: "cm3",
    mission_id: "m2",
    author_id: "u5",
    body: "Merci, quelques ajustements sur le ton des posts LinkedIn.",
    mentions: [],
    created_at: "2026-07-21T14:41:00Z",
  },
];

export const calendarEvents: CalendarEvent[] = missions.map((m) => ({
  id: `ev-${m.id}`,
  title: m.title,
  date: m.deadline,
  type: "mission",
  mission_id: m.id,
}));

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "livrable",
    title: "Nouveau livrable déposé",
    body: "Nadia a déposé « Plan-editorial-Q3.pdf » (v2).",
    read: false,
    created_at: "2026-07-30T16:10:00Z",
    link: "/livrables",
  },
  {
    id: "n2",
    type: "retard",
    title: "Mission en retard",
    body: "« Setup campagnes Meta Ads » a dépassé sa deadline.",
    read: false,
    created_at: "2026-07-30T08:00:00Z",
    link: "/missions",
  },
  {
    id: "n3",
    type: "commentaire",
    title: "Nouveau commentaire",
    body: "Omar Benjelloun a commenté « Plan éditorial réseaux sociaux ».",
    read: true,
    created_at: "2026-07-29T11:22:00Z",
    link: "/missions",
  },
  {
    id: "n4",
    type: "validation",
    title: "Livrable validé",
    body: "« Charte-print-preview.png » a été validé par le client.",
    read: true,
    created_at: "2026-07-28T17:45:00Z",
    link: "/livrables",
  },
];

export const monthlyEvolution = [
  { month: "Fév", missions: 12, livrables: 8 },
  { month: "Mar", missions: 18, livrables: 13 },
  { month: "Avr", missions: 15, livrables: 11 },
  { month: "Mai", missions: 22, livrables: 17 },
  { month: "Juin", missions: 27, livrables: 21 },
  { month: "Juil", missions: 31, livrables: 24 },
];
