# Generated by Django 5.1.4 on 2026-08-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mission_creee', 'Mission créée'), ('mission_assignee', 'Mission assignée'), ('commentaire', 'Commentaire'), ('livrable', 'Livrable'), ('validation', 'Validation'), ('correction', 'Correction'), ('retard', 'Retard')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='missions.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
