# Generated by Django 5.1.4 on 2026-08-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
    ]
