# Generated by Django 5.1.4 on 2026-08-18 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('zip', 'ZIP'), ('video', 'Vidéo'), ('lien', 'Lien')], max_length=10)),
                ('url', models.URLField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('corrections', 'Corrections')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='missions.mission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_deliverables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
