# Generated by Django 5.1.4 on 2026-08-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='url',
            field=models.TextField(),
        ),
    ]
