# Generated by Django 5.1.4 on 2026-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo_url',
            field=models.TextField(blank=True),
        ),
    ]
