# Generated by Django 5.1.4 on 2026-08-18 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('livrable_depose', 'Livrable déposé'), ('validation_interne', 'Validation interne'), ('envoye_client', 'Envoyé au client'), ('valide', 'Validé'), ('corrections', 'Corrections demandées'), ('publie', 'Publié'), ('termine', 'Terminé')], default='a_faire', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_missions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
