# Generated by Django 5.1.4 on 2026-08-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='strategy',
        ),
    ]
