# Generated by Django 5.1.4 on 2026-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_mission_reset_priority_on_termine'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='task_type',
            field=models.CharField(choices=[('mission', 'Mission'), ('editos', 'Editos'), ('livrable', 'Livrable'), ('reunion', 'Réunion')], default='mission', max_length=20),
        ),
    ]
